// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names, unused_field, library_private_types_in_public_api

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:css_inline_dart/src/rust_bindings.g.dart')
library;

import 'dart:ffi' as ffi;

/// Inlines the CSS a document carries in its own style and link tags.
/// `options_json` may be NULL for the defaults.
/// Returns NULL on failure; call `css_inline_last_error` for the reason.
/// The caller must free the result with `css_inline_free_string`.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<ffi.Char> css_inline_document(
  ffi.Pointer<ffi.Char> html,
  ffi.Pointer<ffi.Char> options_json,
);

/// Inlines `css` into `html`, treating it as a fragment rather than a document.
/// Returns NULL on failure; call `css_inline_last_error` for the reason.
/// The caller must free the result with `css_inline_free_string`.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> css_inline_fragment(
  ffi.Pointer<ffi.Char> html,
  ffi.Pointer<ffi.Char> css,
  ffi.Pointer<ffi.Char> options_json,
);

/// Why the last call on this thread returned NULL, or NULL if it succeeded.
/// Owned by the library; valid until the next call on the same thread.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> css_inline_last_error();

/// Frees a string this library returned.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void css_inline_free_string(ffi.Pointer<ffi.Char> ptr);

/// Whether this build can fetch stylesheets over the network.
@ffi.Native<ffi.Int Function()>()
external int css_inline_supports_remote_stylesheets();
